// <auto-generated />
using System;
using Extranet_Financeiro.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Extranet_Financeiro.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Extranet_Financeiro.Domain.AnoSemestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Descricao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnoSemestres");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.PoloRelatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Devolucao")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoloId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcDevPolo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcDevSenacrs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcPolo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcSenacrs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RelatorioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioId");

                    b.ToTable("PoloRelatorios");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.PoloTurma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("Devolucao")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<double>("PercenPolo")
                        .HasColumnType("float");

                    b.Property<double>("PercenSenacrs")
                        .HasColumnType("float");

                    b.Property<int>("PoloRelatorioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcDevPolo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcDevSenacrs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcPolo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcSenacrs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Turma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PoloRelatorioId");

                    b.ToTable("PoloTurmas");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Devolucao")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcDevPolo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcDevSenacrs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcPolo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcSenacrs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.PoloRelatorio", b =>
                {
                    b.HasOne("Extranet_Financeiro.Domain.Relatorio", "Relatorio")
                        .WithMany("Polo")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.PoloTurma", b =>
                {
                    b.HasOne("Extranet_Financeiro.Domain.PoloRelatorio", "PoloRelatorio")
                        .WithMany("PoloTurma")
                        .HasForeignKey("PoloRelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoloRelatorio");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.PoloRelatorio", b =>
                {
                    b.Navigation("PoloTurma");
                });

            modelBuilder.Entity("Extranet_Financeiro.Domain.Relatorio", b =>
                {
                    b.Navigation("Polo");
                });
#pragma warning restore 612, 618
        }
    }
}
